name: test
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - run: echo "file" > file.txt
      - run: ls
      - run: pwd
      - name: Upload file
        uses: actions/upload-artifact@v3
        with: 
          name: file.txt
          path: file.txt
      